config/routes.rb
Wgapp::Application.routes.draw do

  #devise_for :users #, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  devise_for :users

  resources :wgs, :users, :buyings

  root :to => 'wgs#index'

  resources :wgs do
    get 'show', :on => :collection
    get :join_wg, :on => :member, :as => 'join_wg'
    get :change_wg, :on => :member, :as => 'change_wg'
  end

end

app/models/buying.rb
class Buying < ActiveRecord::Base
    belongs_to :user

    validates :description, :presence => true
    validates :costs, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Authenticatable is always included
  devise :recoverable, :validatable, :registerable, :database_authenticatable

  attr_accessible :name, :email, :password, :password_confirmation

  belongs_to :wg
  has_many :buyings

  def buyings_sum()
    buyings.sum('costs')
  end 

  def buyings_destroy()
    buyings.each do |c|
        c.destroy
    end
  end

end

app/models/wg.rb
class Wg < ActiveRecord::Base
  has_many :users

  validates :name, :presence => true
  
  attr_accessible :id, :name, :description, :date, :reset

  def calculate_costs(current_user)
    sumu = 0

    users.each do |c|
      sumu += c.buyings_sum()
    end

    avg_wg = sumu/users.count
    user_costs = current_user.buyings_sum()
    costs = user_costs - avg_wg
  end 

  def credit_or_debit(costs)
    if costs > 0 
      "HABEN"
    else 
      "SOLL"
    end 
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buyings_controller.rb
class BuyingsController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!

  def show
    @buyings = u.buyings
  end

  def new
    @buying = Buying.new
  end

  def create
    @buying = Buying.new(params[:buying])
    current_user.buyings << @buying
  
    if current_user.save 
      redirect_to wgs_path, :notice => 'Einkauf wurde gespeichert.'
    else 
      redirect_to wgs_path, :notice => 'Einkauf konnte nicht gespeichert werden.'
    end
    
  end
  
  def edit
    @buying = Buying.find(params[:id])
  end

  def destroy
    @buying = Buying.find(params[:id])
    @buying.destroy
    redirect_to wgs_path
  end
  
  def update
    @buying = Buying.find(params[:id])
    @buying.update_attributes(params[:buying])
    respond_with(wgs_path)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(params[:wg])
    @user.save
    redirect_to users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to wgs_path
  end

  def show 
    @wg = current_user.wg
  end 

end

app/controllers/wgs_controller.rb
class WgsController < ApplicationController
  
  before_filter :authenticate_user!

  def index
    @wgs = Wg.all
    @wg = current_user.wg
    if @wg.nil? 
    else 
      redirect_to @wg
    end
  end

  def new
    @wg = Wg.new
  end

  def create
    current_user.build_wg(params[:wg])
    current_user.save
    redirect_to wgs_path
  end

  def join_wg
    @wg = Wg.find(params[:id])
    current_user.wg=(@wg)
    current_user.save
    redirect_to @wg
  end

  def show 
    @wg = Wg.find(params[:id])
    @costs = @wg.calculate_costs(current_user)
    @finances = @wg.credit_or_debit(@costs)
  end

  def change_wg
    current_user.wg = nil
    current_user.save
    current_user.buyings_destroy()
    redirect_to wgs_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyings_helper.rb
module BuyingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wgs_helper.rb
module WgsHelper
end

app/views/buyings/_buying.html.erb
<%= div_for buying do %>
<div class="sub_entry" id="">
    <div class="item-left left">

      <span class="value"><%= best_in_place buying, :costs, :html_attrs => { :style => "width:30px;" } %></span>
              
        
    <div class="delete left" title="Eintrag löschen" onClick=""><%= link_to image_tag('images/delete_normal.png', :border => 0, :mouseover=>'images/delete_hover.png'), buying, :confirm => "Are you sure?",
:method => :delete %></div>

    </div>
    <div class="comment left"><%= best_in_place buying, :description, :html_attrs => { :style => "width:180px;" } %></div>
    <div style="clear:both;"></div>
    <div class="sub_entry_line"></div>
</div>

<% end %>

app/views/buyings/_edit.html.erb
<div id="edit_popup">

<div id="edit_blue">
	<h1>Eintrag bearbeiten</h1>
</div>

<div id="edit_form">

<%= form_for @buying, :as => :buying, :url => buyings_path do |f| %>
  <p>
	<%= f.label :costs %> 
	<%= f.text_field :costs %> €
  </p>
  <p>
	<%= f.label :description %>
	<%= f.text_area :description %>
  </p>
  <p>
	<%= f.submit 'Submit' %>
  </p>
<% end %>

</div>

</div>

app/views/buyings/_new.erb
<div id="eintrag_form">

<%= form_for @buying, :as => :buying, :url => buyings_path do |f| %>
 <p>
    <%= f.label :costs %> 
    <%= f.text_field :costs %> €
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

</div>  

app/views/buyings/edit.html.erb
<div id="edit_popup">

<div id="edit_blue">
	<h1>Eintrag bearbeiten</h1>
</div>

<div id="edit_form">

<%= form_for (@buying) do |f| %>
  <p>
	<%= f.label :costs %> 
	<%= f.text_field :costs %> €
  </p>
  <p>
	<%= f.label :description %>
	<%= f.text_area :description %>
  </p>
  <p>
	<%= f.submit 'Submit' %>
  </p>
<% end %>

</div>

</div>

app/views/buyings/index.html.erb
<h1>Buyings#index</h1>
<p>Find me in app/views/buyings/index.html.erb</p>

app/views/buyings/new.html.erb
<h1>Buyings#new</h1>
<p>Find me in app/views/buyings/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WG-App</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <div class="alert_wrapper"><span class="notice"><%= flash[:notice] %></span></div>
  <div class="alert_wrapper"><span class="notice"><%= notice %></span></div>
  <div class="alert_wrapper"><span class="alert"><%= flash[:alert] %></span></div>
  <div class="alert_wrapper"><span class="alert"><%= alert %></span></div>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
<%= div_for user do %>
<div class="content_box">
    <div class="content_box_top left">
        <h2><%= user.name %><%= link_to image_tag('images/delete_normal.png', :border => 0, :mouseover=>'images/delete_hover.png'), user, :confirm => "Are you sure?",
:method => :delete %></h2>
    </div>
    <div class="content_box_schrage left"></div> 
    <div style="clear:both"></div>
    <div class="content_box_contentWrapper">

    <div class="month" id="">
           <span>Jänner</span><span class="arrow right open"></span>
      </div>

      <div class="entry" id="">
            
            <%= render user.buyings %>
            
          <div class="monthly-sum">Summe: <%= user.buyings_sum() %>€&nbsp;<span style="font-size:16px"></span></div>

      </div>
    </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "Neuer User", new_user_path %>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> | <%= user.email %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Neuer User</h1>

<%= form_for(@user) do |f| %>
  <p>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit "Speichern" %>
  </p>
<% end %>

<%= link_to "Zurück", users_path %>

app/views/wgs/index.html.erb
<div id="content">
    <nav>
        <header>
            <div class="header_logout"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></div>
            <div class="header_title"><%= link_to "Neue WG", new_wg_path %></div>
        </header>
    </nav>

    <div style="clear: both;"></div>

    <div class="main">

<br/><h3>Join a WG</h3></br>

<ul class="wgs">
  <% @wgs.each do |wg| %>
    <%= wg.id %>
    <li>
    
        <%= link_to wg.name, join_wg_wg_path(wg) %> | <%= wg.date %>
    
    </li>


  <% end %>
</ul>

</div>
</div>

app/views/wgs/new.html.erb
<div id="content">
    <nav>
        <header>
            <div class="header_logout"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></div>
            <div class="header_title"><%= link_to "Join WG", wgs_path %></div>
        </header>
    </nav>

    <div style="clear: both;"></div>

    <div class="main">

<br/>
    <h3>Neue WG</h3>

    <div style="line-height: 30px;">
    <%= form_for(@wg) do |f| %>
      <p>
        <%= f.label :name %> 
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :description %> 
        <%= f.text_field :description %>
      </p>
      <p>
        <%= f.submit "Speichern" %>
      </p>
    <% end %>
    </div>
    </div>
</div>

app/views/wgs/show.html.erb
<div id="content">
    <nav>
        <header>
            <div class="header_logout"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></div>
            <div class="move_to"><%= link_to 'Move into other wg', change_wg_wg_path %></div>
            <div class="header_title"><%= @wg.name %> </div>
            <div class="signedinas">Signed in as <%= current_user.name %></div>
        </header>
    </nav>

    <div style="clear: both;"></div>

    <div class="main">

        <div class="content_header">
            <div class="info_box">
                <span class="info_box_top"></span>
                <div class="info_box_content">
                    <p>Immer schön benutzen damit die Arbeit nicht umsonst war!</p>
                    <p class="box_line_height">Rechts kannst du einen <span>neuen Eintrag</span> machen!</p><br />
                </div>
                <span class="info_box_bottom"></span>
            </div>

            <%= render 'buyings/new' %>
            
            <div style="clear: both;"></div>    
        </div>

        <div class="clear"></div>
        <div id="diff">
            <div class="diff_box">
                <div class="diff_name">Soviel bist du im <%= @finances %>:</div>
                <div class="diff_value <%= @finances %>"><%= @costs %></div>
               
            </div>
        </div>
        
        <%= render @wg.users %>

        <div style="clear:both"></div>
        
        


    </div>

</div>